# Generated by Django 2.0 on 2017-12-24 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('description', models.TextField()),
                ('art_name', models.CharField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att_key', models.CharField(max_length=256)),
                ('att_value', models.CharField(max_length=2048)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('description', models.TextField()),
                ('chap_no', models.IntegerField()),
                ('chap_title', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('description', models.TextField()),
                ('chara_whole_name', models.CharField(max_length=512)),
                ('chara_nickname', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharacterOccupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('cocc_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scriptus_write.Character')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_name', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Started'), (2, 'Draft'), (3, 'Work In Progress'), (4, 'Beta'), (5, 'Done')])),
                ('idea_name', models.CharField(max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('description', models.TextField()),
                ('loc_name', models.CharField(max_length=128)),
                ('loc_latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('loc_longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('loc_altitude', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('description', models.TextField()),
                ('occ_name', models.CharField(max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('part_name', models.CharField(max_length=512)),
                ('part_number', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('description', models.TextField()),
                ('rel_char1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char1_related', to='scriptus_write.Character')),
                ('rel_char2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char2_related', to='scriptus_write.Character')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('description', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Started'), (2, 'Draft'), (3, 'Work In Progress'), (4, 'Beta'), (5, 'Done')])),
                ('scene_title', models.CharField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SceneCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scriptus_write.Character')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scriptus_write.Scene')),
            ],
        ),
        migrations.CreateModel(
            name='SceneFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sf_name', models.CharField(max_length=512)),
                ('sf_end_scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sc_frame_end_related', to='scriptus_write.Scene')),
                ('sf_start_scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sc_frame_start_related', to='scriptus_write.Scene')),
            ],
        ),
        migrations.CreateModel(
            name='SceneLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scriptus_write.Location')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scriptus_write.Scene')),
            ],
        ),
        migrations.CreateModel(
            name='SceneStrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scriptus_write.Scene')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('shortname', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('description', models.TextField()),
                ('strand_name', models.CharField(max_length=512)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scriptus_write.Story')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tf_name', models.CharField(max_length=512)),
                ('tf_start', models.DateTimeField(null=True)),
                ('tf_end', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='scenestrand',
            name='strand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scriptus_write.Strand'),
        ),
        migrations.AddField(
            model_name='scene',
            name='scene_mainstrand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scriptus_write.Strand'),
        ),
        migrations.AddField(
            model_name='scene',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scriptus_write.Story'),
        ),
        migrations.AddField(
            model_name='scene',
            name='timeframe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scene_fit_related', to='scriptus_write.TimeFrame'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='rel_scene_frame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scriptus_write.SceneFrame'),
        ),
        migrations.AddField(
            model_name='occupation',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scriptus_write.Story'),
        ),
        migrations.AddField(
            model_name='location',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scriptus_write.Story'),
        ),
        migrations.AddField(
            model_name='location',
            name='timeframe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_fit_related', to='scriptus_write.TimeFrame'),
        ),
        migrations.AddField(
            model_name='idea',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scriptus_write.Story'),
        ),
        migrations.AddField(
            model_name='gender',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scriptus_write.Story'),
        ),
        migrations.AddField(
            model_name='characteroccupation',
            name='cocc_occupation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scriptus_write.Occupation'),
        ),
        migrations.AddField(
            model_name='characteroccupation',
            name='timeframe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characteroccupation_fit_related', to='scriptus_write.TimeFrame'),
        ),
        migrations.AddField(
            model_name='character',
            name='chara_gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scriptus_write.Gender'),
        ),
        migrations.AddField(
            model_name='character',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scriptus_write.Story'),
        ),
        migrations.AddField(
            model_name='character',
            name='timeframe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='character_fit_related', to='scriptus_write.TimeFrame'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scriptus_write.Story'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scriptus_write.Story'),
        ),
    ]
